const list = [
    {
      id: 1,
      title: "Puma Womens Agile Trip WN's Idp Sneaker",
      brand: "PUMA",
      price: 2449,
      description:"Sole: Rubber /Closure: Lace-Up / Fit Type: Regular /Shoe Width: Medium /Style Name:- Sneaker / Model Name:-Agile Trip Wn s IDP /Brand Color:-Eggshell Blue-Puma White /Wipe with a clean dry cloth",
      img: "https://m.media-amazon.com/images/I/81o6N9YnUmL._UL1500_.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "Campus Men Triggeer Black Running Shoes",
      brand: "CAMPUS",
      price: 1299,
      description: "Sole: Phylon /Closure: Lace-Up /Fit Type: Relaxed /Shoe Width: Medium / Light Weight /Attractive look /Comfortable for your feet /Allow your pair of shoes to air and de-odorize at a regular basis, this also helps them retain their natural shape; use shoe bags to prevent any stains or mildew; dust any dry dirt from the surface using a clean cloth, do not use polish or shine",
      img: "https://m.media-amazon.com/images/I/81fM+-EEgiL._UL1500_.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Adidas Mens Adispree 2.0 M Running Shoes",
      brand: "ADIDAS",
      price: 2089,
      description:"Sole: Ethylene Vinyl Acetate/ Closure: Lace-Up/ Fit Type: Regular /Shoe Width: Medium / This product runs a size small. If you usually buy UK 9, buy UK 10 for this /Material Type: Mesh /Lifestyle: Casual",
      img: "https://m.media-amazon.com/images/I/81MaROqd42L._UL1500_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "in Men's sneakers",
      brand: "RED TAPE",
      price: 1517,
      description:"Sole: EVA + TPR + TPU Closure: Lace-Up /Fit Type: Relaxed /Shoe Width: Medium /Closure:Lace-Up /Type:Sneakers/ Upper Material:MESH + PU/Sole Material:EVA + TPR + TPU",
      img: "https://m.media-amazon.com/images/I/319cxksfZAL.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Fila Men's Carmen Plus Charcoal Sport Shoes",
      brand: "FILA",
      price: 1999,
      description:"Care Instructions: Wipe with a clean- dry cloth when needed /Fit Type: Regular /UPPER MATERIAL - PU /SOLE MATERIAL - EVA/  FASTENING - Lace-up/  TOE SHAPE - Round/ Color - Red",
      img: "https://m.media-amazon.com/images/I/61H849SA6TL._UL1500_.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "LANCER Mens Indus-215 Hiking Shoe",
      brand: "LANCER",
      price: 899,
      description:"Sole: Ethylene Vinyl Acetate /Closure: Lace-Up/ Fit Type: Regular /Shoe Width: Medium/ Sole Material: EVA/ Inner Material: Comfort Insole/ Upper Material: Mesh",
      img: "https://m.media-amazon.com/images/I/71Uqcsss4lL._UL1500_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Nike Mens Downshifter 12 Running",
      brand: "NIKE",
      price: 3499,
      description:"Sole: Rubber /Closure: Lace-Up /Shoe Width: Medium /NIKE DOWNSHIFTER 12-BLACK/LIGHT SILVER-FADED SPRUCE-DD9293-010-8UK",
      img: "https://m.media-amazon.com/images/I/31MvVn+CV9L.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Womens Sl-226 Sneaker",
      brand: "SPARX",
      price: 1349,
      description:"Sole: Phylon /Closure: Lace-Up/ Fit Type: Regular/ Shoe Width: Medium/ WHAT YOU GET: 1. One Pair of Sports Shoes as shown in the pictures. 2. Storage Box. 3. Sparx Trust./ MADE OF: High Quality Mesh as upper material and Phylon as sole material. /KEY FEATURES: Made to Last Long, Elegant Packaging, Perfect Gifting Option, Zero compromise on quality",
      img: "https://m.media-amazon.com/images/I/818nDrSuTDL._UL1500_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Mens W3011 156 Walking Shoes ",
      brand: "FURO",
      price: 3489,
      description:"Sole: Rubber/ Closure: Lace-Up/ Heel Height: 1 centimeters /Fit Type: Regular/ Shoe Width: Medium /Mesh",
      img: "https://m.media-amazon.com/images/I/71sIUaLTSJL._UL1300_.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: " HY-Court 2.0 Badminton Shoe for Mens ",
      brand: "NIVIA",
      price: 1799,
      description:"Breathable Mesh with Fusion Technology/  Die Cut Soft NR EVA sock liner/ Soft cushion NR EVA Inner sole/ Duofoam Soft compressed midsole with inner shank /Multi Directional Grooves, Round inner sole grooves give more stability",
      img: "https://m.media-amazon.com/images/I/9184zU7s9oL._SX679_.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Badminton Shoes Dominant ",
      brand: "YONEX",
      price:2920,
      description:"Ideal for Badminton,Squash,Table Tennis,Volleyball | Non-Marking Sole |TRU Cushion |Durable Skin Light|Synchro-Fit Insole|Toe Assist Shape|Hexa Grip |Light Weight|",
      img: "https://m.media-amazon.com/images/I/91pQW-kBREL._UL1500_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "YOUNG RS11 Non Marking Badminton Shoe",
      brand: "YOUNG",
      price: 2467,
      description:"RS11 has a breathable AIR SHELL upper for comfort and optimal weight. RS11 also comes with super comfortable cushion sole designed specially for players with high inertial movements.",
      img: "https://m.media-amazon.com/images/I/71pNVZWxquL._SX679_.jpg",
      amount: 1,
    },
];

export default list;